function camera_image_in_dmd_space = map_camera_image_into_dmd_space(camera_image, ...
                                                                     debarrel_parameter, ...
                                                                     transform_to_dmd_space_from_debarreled_camera_space, ...
                                                                     dmd_reference_frame)
                                                                 
    debarreled_camera_image = correct_lens_distortion(camera_image, debarrel_parameter) ;
    camera_image_in_dmd_space = imwarp(debarreled_camera_image, transform_to_dmd_space_from_debarreled_camera_space, 'OutputView', dmd_reference_frame) ;
end
